version: '3'

services:

  db:
    image: postgres:15.3
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_storage
      PGDATA: /data/postgres
    volumes:
      - ./imports/db/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:7.0
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
      REDIS_PORT: 6379

  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-31T20-20-33Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: MINIO
      MINIO_ROOT_PASSWORD: MINIOMINIO

  app:
    build: .
    hostname: app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
    ports:
      - "8080:8080"

