version: '3'

services:

  db:
    image: postgres:15.3
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_storage
    volumes:
      - ./imports/db/:/docker-entrypoint-initdb.d/

  app:
    build: .
    hostname: app
    depends_on:
      - db
    ports:
      - "8080:8080"

